import { faSquare } from '@fortawesome/pro-regular-svg-icons'
import {
  faAlarmClock,
  faAngleDown,
  faArrowAltCircleRight,
  faBan,
  faCaretDown,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faFistRaised,
  faLongArrowLeft,
  faLongArrowRight,
  faPlusCircle,
  faSalad,
  faSirenOn,
  faSpinnerThird,
  faHandSpock,
  faTrashAlt,
  faUndo,
} from '@fortawesome/pro-solid-svg-icons'

const faIcons = [
  faAlarmClock,
  faAngleDown,
  faArrowAltCircleRight,
  faBan,
  faCaretDown,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faFistRaised,
  faLongArrowLeft,
  faLongArrowRight,
  faPlusCircle,
  faSalad,
  faSirenOn,
  faSpinnerThird,
  faHandSpock,
  faSquare,
  faTrashAlt,
  faUndo,
]

export { faIcons }
